### ISSUE TITLE
Translation Vector is dz, dx, dy

### ISSUE THREAD

**Issue by yghlc** [PolarGeospatialCenter/pgcdemtools#12]
https://github.com/PolarGeospatialCenter/pgcdemtools/blob/b663b56937de25f3a507c8d0f4b1edbb52e97ceb/apply_setsm_registration.py#L199-L202

Hello, I downloaded a strip DEM (GE01_20170319_1050010008B59F00_1050010008B59D00_seg1_2m_dem.tif) from PGC and tried to registration the DEM file by applying the Translation Vector. In the *reg.txt file, the Translation Vector is in the order of "dz, dx, dy", but these codes (cited above) phrase them as "dx, dy, dz".

Please check and solve this bug, thank you!

**Comment by ehusby** [comment]
Thank you verify much @yghlc for bringing this important bug to our attention, and sorry for the late response!
This has now been fixed in the master branch.
